title: Jamy Martin # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="https://www.linkedin.com/in/votre-profil/">LinkedIn</a> | 
  <a href="https://votre-lien-vers-le-resume.pdf">Resume</a> | 
  <a href="https://github.com/jam-mar-hub">GitHub</a>
  <br><br>
  I am pursuing a MS degree in Data Science at École Centrale de Lille.
  <br><br>
  I am currently an AI/Data Scientist intern at
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
